<style>
    .upload-image {
        background: #75BAC0;
        border-radius: 5px;
        height: 70px;
        line-height: 66px;
        color: #FFF !important;
        text-align: center;
        font-size: 40px !important;
        width: 330px;
        cursor: pointer;
        font-family: 'Lobster', cursive;
        margin: 300px auto 0;
        box-shadow: inset 0 0 4px #fff;
        -moz-box-shadow: inset 0 0 4px #fff;
        -webkit-box-shadow: inset 0 0 4px #fff;
    }

    #photo-gallery{
        float: left;
    }

    .button-upload {
        border-radius: 5px;
        border: 2px #E7E7E7;
        /*background-color: #F4F4F4;*/
        /* IE10 Consumer Preview */
        background-image: -ms-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* Mozilla Firefox */
        background-image: -moz-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* Opera */
        background-image: -o-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* Webkit (Safari/Chrome 10) */
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #FFFFFF), color-stop(1, #F4F4F4));
        /* Webkit (Chrome 11+) */
        background-image: -webkit-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* W3C Markup, IE10 Release Preview */
        background-image: linear-gradient(to bottom, #FFFFFF 0%, #F4F4F4 100%);
        color: #696969;
        width: 170px;
        height: 60px;
        float: left;
        margin: 15px 15px;
        font-size: large;
        padding-top: 1%;
    }
    .button-upload img {
        margin-left: 7%;
        vertical-align: middle;
    }

    .button-upload span {
    }

    .button-upload p {
        margin-top: 10%;
    }

    .my-computer {
        text-align: center;
        border-radius: 5px;
        border: 2px #E7E7E7;
        /*background-color: #F4F4F4;*/
        /* IE10 Consumer Preview */
        background-image: -ms-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* Mozilla Firefox */
        background-image: -moz-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* Opera */
        background-image: -o-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* Webkit (Safari/Chrome 10) */
        background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0, #FFFFFF), color-stop(1, #F4F4F4));
        /* Webkit (Chrome 11+) */
        background-image: -webkit-linear-gradient(top, #FFFFFF 0%, #F4F4F4 100%);
        /* W3C Markup, IE10 Release Preview */
        background-image: linear-gradient(to bottom, #FFFFFF 0%, #F4F4F4 100%);
        color: #696969;
        width: 170px;
        height: 80px;
        margin-left: 15px;
        width: 370px !important;
        font-size: large;
        padding-top: 1%;
    }
    .my-computer img {
        vertical-align: middle;
    }

    .my-computer span {
    }

    .my-computer p {
        margin-top: 5%;
    }

    #dialog {
        box-shadow: 0 0 10px #000000;
    }

    .instagram-placeholder {
        display: inline;
    }

    .photo-gallery {
        display: inline;
        float: left !important;
        text-align: left !important;
    }

    .photo-gallery img {
        margin-right: 2%;
        margin-bottom: 2%;
    }
</style>
<title>Dialog hide show</title>
<div class="upload-image" id="upload-image">
    Upload Image
</div>

<div id="dialog" title="Where's Your Photo At?" style="display:none;">
    <br />
    <div id="social">
        <div id="my-computer" class="my-computer">
            <p>
                <img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/images/mycomputer.png" title="Upload from your computer" width="50" height="50" />
                <span> My Computer</span>
            </p>
        </div>

        <div id="instagram" class="button-upload">
            <p>
                <img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/images/instagram.jpg" title="Upload from Instagram" width="30" height="30" />
                <span> Instagram</span>
            </p>
        </div>

        <div id="facebook" class="button-upload">
            <p>
                <img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/images/facebook.jpg" title="Upload from Facebook" width="30" height="30" />
                <span>Facebook</span>
            </p>
        </div>

        <br />

        <div id="photobucket" class="button-upload">
            <p>
                <img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/images/photobucket.png" title="Upload from PhotoBucket" width="30" height="30" />
                <span> PhotoBucket</span>
            </p>
        </div>

        <div id="gplus" class="button-upload">
            <p>
                <img src="http://<?php echo $_SERVER['SERVER_NAME']; ?>/images/gplus.png" title="Upload from Google Plus" width="30" height="30" />
                <span>Google Plus</span>
            </p>
        </div>
    </div>

    <div class="photo-gallery"></div>
</div>

<form id="form-my-computer-upload" name="form-my-computer-upload" method="post" action="index/upload?type=my-computer&url=null" enctype="multipart/form-data">
    <input type="file" id="file-input-upload" name="file-input-upload" style="visibility: hidden; width: 1px; height: 1px" />
</form>