<?php
$bannerGroupCode = $this->getBannerGroupCode();
$data = $this->getDataByGroupCode($bannerGroupCode);
$bannerGroupData = $data['group_data'];
$mediaDir = Mage::getBaseDir('media');
$bannerData = $data['banner_data'];
$baneff = $bannerGroupData->getBannerEffects();
$bannerdest = (($bannerGroupData->getLinkTarget() == 0) ? '_blank' : '_self');
$bannerType = $bannerGroupData->getAnimationType();
$bannerWidth = $bannerGroupData->getBannerWidth();
$bannerHeight = $bannerGroupData->getBannerHeight();
$imageWidth = ((int) $bannerWidth - 3);
$imageHeight = ((int) $bannerHeight - 3);
$styleBWH = 'width: ' . $bannerWidth . 'px; height: ' . $bannerHeight . 'px;';
$styleWH = 'width: ' . $imageWidth . 'px; height: ' . $imageHeight . 'px;';
$duration = Mage::getStoreConfig('banner/banner/banner_time_delay');
?>
<script type="text/javascript">
	$(function() {
		/*$('img.image1').data('ad-desc', 'Whoa! This description is set through elm.data("ad-desc") instead of using the longdesc attribute.<br>And it contains <strong>H</strong>ow <strong>T</strong>o <strong>M</strong>eet <strong>L</strong>adies... <em>What?</em> That aint what HTML stands for? Man...');
		$('img.image1').data('ad-title', 'Title through $.data');
		$('img.image4').data('ad-desc', 'This image is wider than the wrapper, so it has been scaled down');
		$('img.image5').data('ad-desc', 'This image is higher than the wrapper, so it has been scaled down');*/
		var galleries = $('.ad-gallery').adGallery();
		/*setTimeout(function() {
		  galleries[0].addImage("images/thumbs/t7.jpg", "images/7.jpg");
		}, 1000);
		setTimeout(function() {
		  galleries[0].addImage("images/thumbs/t8.jpg", "images/8.jpg");
		}, 2000);
		setTimeout(function() {
		  galleries[0].addImage("images/thumbs/t9.jpg", "images/9.jpg");
		}, 3000);
		setTimeout(function() {
		  galleries[0].removeImage(1);
		}, 4000);*/
		
		$('#switch-effect').change(
			function() {
				galleries[0].settings.effect = $(this).val();
				return false;
			}
		);
		$('#toggle-slideshow').click(
			function() {
				galleries[0].slideshow.toggle();
				return false;
			}
		);
		$('#toggle-description').click(
			function() {
				if(!galleries[0].settings.description_wrapper) {
					galleries[0].settings.description_wrapper = $('#descriptions');
				} else {
					galleries[0].settings.description_wrapper = false;
				}
				return false;
			}
		);
	});
</script>
<div id="gallery" class="ad-gallery">
    <div class="ad-image-wrapper">
    </div>
    <div class="ad-controls">
    </div>
    <div class="ad-nav">
        <div class="ad-thumbs">
			<ul class="ad-thumb-list">
			<?php
				$i = 0;
				foreach ($bannerData as $banner):
					$i++;
					$bannerType = $banner->getBannerType();
					$bannerTitle = $banner->getTitle();
					$bannerContent = $banner->getBannerContent();
					$bannerLink = $banner->getLink();
					$v = "img" . $i;
					if ($bannerType == 0) :
						$bannerPath = $banner->getFilename();
						$bannerImage = '';
						if ($bannerPath != '' && @file_exists($mediaDir . DS . $bannerPath)):
							$bannerImage = $this->getResizeImage($bannerPath, $bannerGroupCode, $imageWidth, $imageHeight);
						endif;
						if ($bannerImage != '') :
				?>
						<li><a href="<?php echo $bannerImage; ?>"  <?php echo (($bannerLink)?'target="'.$bannerdest.'"':''); ?>  title="<?php echo $bannerTitle; ?>"><img width="90px" height="60px" src="<?php echo $bannerImage; ?>" alt="<?php echo $bannerTitle; ?>" /></a></li>
				<?php
						endif;
					endif;
				endforeach; ?>
			</ul>
        </div>
    </div>
</div>
<div id="descriptions">
</div>